version: "3"
services:
  app:
    build: .
    container_name: app
    restart: unless-stopped
    env_file: ".env"
    ports:
      - "80:8080"
    networks:
      - app-network
  webserver:
    image: nginx:latest
    container_name: webserver
    restart: unless-stopped
    ports:
      - "80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge 
