on: [push]
name: 'Azure Container App Workflow'

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:
        # checkout the repo
        - name: 'Checkout GitHub Action'
          uses: actions/checkout@main
          
        - name: 'Login via Azure CLI'
          uses: azure/login@v1
          with:
            creds: ${{ secrets.AZURE_CREDENTIALS }}

        - name: Build and deploy Container App
          uses: azure/container-apps-deploy-action@v1
          with:
            appSourcePath: ${{ github.workspace }}
            acrName: ${{ secrets.REGISTRY_NAME }}
            containerAppName: ${{ secrets.APP_NAME }}
            resourceGroup: ${{ secrets.RESOURCE_GROUP }}
            acrUsername: ${{ secrets.REGISTRY_USERNAME }}
            acrPassword: ${{ secrets.REGISTRY_PASSWORD }}
            environmentVariables: DOTENV_KEY=secretref:${{ secrets.DOTENV_KEY }}
